#qsub clipOverlaps.sh J432_AHHH5NBCXX_Lane1_ACAGTG_HPNE-1_BS_merged_sorted_mdup_nsorted.bam
#qsub clipOverlaps.sh J432_AHHH5NBCXX_Lane2_GCCAAT_HPNE-1OxBS_merged_sorted_mdup_nsorted.bam
#qsub clipOverlaps.sh J432_BHKVCGBCXX_Lane1_CTTGTA_JD-BS_merged_sorted_mdup_nsorted.bam
#qsub clipOverlaps.sh J432_BHKVCGBCXX_Lane2_GTGAAA_JD-OxBS_merged_sorted_mdup_nsorted.bam

./clipOverlaps_mycomp.sh J432_AHHH5NBCXX_Lane1_ACAGTG_HPNE-1_BS_merged_sorted_mdup.bam
./clipOverlaps_mycomp.sh J432_AHHH5NBCXX_Lane2_GCCAAT_HPNE-1OxBS_merged_sorted_mdup.bam
./clipOverlaps_mycomp.sh J432_BHKVCGBCXX_Lane1_CTTGTA_JD-BS_merged_sorted_mdup.bam
./clipOverlaps_mycomp.sh J432_BHKVCGBCXX_Lane2_GTGAAA_JD-OxBS_merged_sorted_mdup.bam

